# Generated by Django 4.1.2 on 2022-10-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('role', models.CharField(choices=[('member', 'участник'), ('moderator', 'модератор'), ('admin', 'администратор')], max_length=10, verbose_name='Роль')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст, полных лет')),
                ('locations', models.ManyToManyField(related_name='users', to='locations.location', verbose_name='Локации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
