# Generated by Django 4.1.2 on 2022-10-28 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('role', models.CharField(choices=[('member', 'участник'), ('moderator', 'модератор'), ('admin', 'администратор')], max_length=10, verbose_name='Роль')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст, полных лет')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ads.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заготовок')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='Было опубликовано?')),
                ('image', models.FilePathField(null=True, verbose_name='Картинка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.user', verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.category', verbose_name='Категория')),
            ],
        ),
    ]
