# Generated by Django 4.1.2 on 2022-10-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
