# Generated by Django 4.1.2 on 2022-10-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_location_lat_location_lng_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.FilePathField(null=True, path='./static/', verbose_name='Картинка'),
        ),
    ]
