# Generated by Django 4.1.2 on 2022-10-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ManyToManyField(related_name='users', to='ads.location', verbose_name='Локации'),
        ),
    ]
