# Generated by Django 4.1.2 on 2022-10-28 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('ads', '0007_rename_location_user_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='categories.category', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
