# Generated by Django 4.1.2 on 2022-10-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_delete_location_alter_user_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='locations',
        ),
    ]
