# Generated by Django 4.1.2 on 2022-10-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_alter_ad_author_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Картинка'),
        ),
    ]
