# Generated by Django 4.1.2 on 2022-10-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_alter_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
