# Generated by Django 4.1.2 on 2022-10-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Адрес')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Широта')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
    ]
